### ISSUE TITLE
Set handlers in pillar

### ISSUE THREAD

**Issue by mattmb** [ministryofjustice/sensu-formula#24]
A reminder to myself

Put ability to set handler in pillar, allow override in macro.

eg.
```
sensu:
  checks:
    load:
      handlers: ['hipchat']
```
